### ISSUE TITLE
Do we have a translation plan?

### ISSUE THREAD

**Issue by JellyBool** [Joohansson/nanolinks#9]
Hi, I think I can do a Chinese translation for nanolinks. Do we have a plan?

**Comment by Joohansson** [comment]
Hi, the idea is tempting but I can't figure out right now how to maintain it. I do daily updates to this repo and it would be out of sync. I would also have no idea what it actually says =)

Also, almost all pages it links to are in english. Are translation really needed? I also don't know how it would be presented and I want to stay as simple as possible and easy for users to edit.

Will all that in mind, I don't think we need a translation, but I'm open for ideas!
